-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('STUDENT_DROPPED_FROM_COURSE', 'STUDENT_KICKED_FROM_COURSE', 'STUDENT_ENROLLED_IN_COURSE', 'STUDENT_REJECTED_ENROLLMENT_FROM_COURSE', 'COURSE_CREATED', 'COURSE_UPDATED', 'COURSE_DELETED', 'COURSE_COMPLETED');

-- CreateTable
CREATE TABLE "events" (
    "id" SERIAL NOT NULL,
    "type" "EventType" NOT NULL,
    "payload" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "events" ADD CONSTRAINT "events_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
